# Generated by Django 5.2.1 on 2025-05-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partesproduto",
            name="produto",
        ),
        migrations.AddField(
            model_name="produto",
            name="partes",
            field=models.ManyToManyField(blank=True, to="core.partesproduto"),
        ),
    ]
