# Generated by Django 5.2.1 on 2025-05-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_partesproduto_produto_produto_partes"),
    ]

    operations = [
        migrations.AddField(
            model_name="partesproduto",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="partesproduto",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
