# Generated by Django 5.2.1 on 2025-05-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_partesproduto_ativo_partesproduto_preco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partesproduto",
            name="imagem",
            field=models.ImageField(max_length=400, upload_to="partes_produto/"),
        ),
    ]
