# Generated by Django 5.2.1 on 2025-05-17 01:29

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_partesproduto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="partesproduto",
            name="codigo",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234", length=7, max_length=7, prefix="pr", unique=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234", length=7, max_length=7, prefix="pr", unique=True
            ),
        ),
    ]
