# Generated by Django 5.2.1 on 2025-05-17 01:32

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_partesproduto_codigo_produto_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partesproduto",
            name="codigo",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                editable=False,
                length=7,
                max_length=9,
                prefix="pr",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                editable=False,
                length=7,
                max_length=9,
                prefix="pr",
                unique=True,
            ),
        ),
    ]
