# Generated by Django 5.2.1 on 2025-05-17 01:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_partesproduto_codigo_alter_produto_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partesproduto",
            name="imagem",
            field=models.ImageField(
                max_length=400, upload_to=core.models.get_path_partes_produto_imagem
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                max_length=400, upload_to=core.models.get_path_produto_imagem
            ),
        ),
    ]
