# Generated by Django 5.2.1 on 2025-05-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_partesproduto_imagem_alter_produto_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partesproduto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
