# Generated by Django 5.2.1 on 2025-05-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_partesproduto_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="partes_produto",
            field=models.ManyToManyField(blank=True, to="core.partesproduto"),
        ),
    ]
