# Generated by Django 5.2.1 on 2025-05-17 02:14

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pedido_partes_produto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="partes_produto",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="produto",
        ),
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="codigo",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                editable=False,
                length=7,
                max_length=9,
                prefix="pe",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        editable=False,
                        length=7,
                        max_length=9,
                        prefix="cr",
                        unique=True,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "partes_produto",
                    models.ManyToManyField(blank=True, to="core.partesproduto"),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.produto"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrinho",
                "verbose_name_plural": "Carrinhos",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
