# Generated by Django 5.2.1 on 2025-05-17 02:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_pedido_partes_produto_remove_pedido_produto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Carrinho",
            new_name="PedidoItems",
        ),
        migrations.AlterModelOptions(
            name="pedidoitems",
            options={
                "ordering": ["-data_criacao"],
                "verbose_name": "Pedido Items",
                "verbose_name_plural": "PedidoItems",
            },
        ),
    ]
