# Generated by Django 5.2.1 on 2025-05-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_carrinho_pedidoitems_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="items",
            field=models.ManyToManyField(blank=True, to="core.pedidoitems"),
        ),
    ]
