# Generated by Django 5.2.1 on 2025-05-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_pedido_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedidoitems",
            name="usuario",
        ),
    ]
