# Generated by Django 5.2.1 on 2025-05-18 03:24

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_pedidoitems_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFluxo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        editable=False,
                        length=7,
                        max_length=9,
                        prefix="fl",
                        unique=True,
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("resposta", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Fluxo",
                "verbose_name_plural": "Chat Fluxos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        editable=False,
                        length=7,
                        max_length=9,
                        prefix="ch",
                        unique=True,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etapa_fluxo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.chatfluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="ChatMensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        editable=False,
                        length=7,
                        max_length=9,
                        prefix="ms",
                        unique=True,
                    ),
                ),
                ("mensagem", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="core.chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Mensagem",
                "verbose_name_plural": "Chat Mensagens",
                "ordering": ["data_criacao"],
            },
        ),
    ]
