# Generated by Django 5.2.1 on 2025-05-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_chatfluxo_chat_chatmensagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatfluxo",
            name="etapa_fluxo",
            field=models.CharField(default="", max_length=100),
        ),
    ]
