# Generated by Django 5.2.1 on 2025-05-18 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_chatfluxo_etapa_fluxo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="etapa_fluxo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fluxo",
                to="core.chatfluxo",
            ),
        ),
    ]
