# Generated by Django 5.2.1 on 2025-05-18 03:44

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_chat_etapa_fluxo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFluxoOpcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        editable=False,
                        length=7,
                        max_length=9,
                        prefix="fo",
                        unique=True,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "fluxo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fluxo_opcoes",
                        to="core.chatfluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Fluxo Opcao",
                "verbose_name_plural": "Chat Fluxo Opcoes",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
