# Generated by Django 5.2.1 on 2025-05-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_chatfluxoopcao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatfluxoopcao",
            old_name="fluxo",
            new_name="etapa_fluxo",
        ),
    ]
