# Generated by Django 5.2.1 on 2025-05-18 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_chatfluxo_titulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatfluxoopcao",
            name="fluxo_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fluxo_opcao_destino",
                to="core.chatfluxo",
            ),
        ),
    ]
